services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: GodBl3ssTlum9
    expose:
      - 3306
    networks:
      jh-network:
        ipv4_address: 172.19.0.11
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GodBl3ssTlum9
    networks:
      jh-network:
        ipv4_address: 172.19.0.12

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      # ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_BASICAUTH_USERNAME    : ''              
      # ME_CONFIG_BASICAUTH_PASSWORD    : ''              
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'          
      # ME_CONFIG_MONGODB_PORT          : 27017           
      # ME_CONFIG_MONGODB_SERVER        : 'mongo'         
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:GodBl3ssTlum9@172.19.0.12:27017/
    networks:
      jh-network:
        ipv4_address: 172.19.0.15

  pma:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=GodBl3ssTlum9
      - PMA_ROOT_PASSWORD=GodBl3ssTlum9
      - PMA_PORT=3306
      - PMA_ALLOW_NO_USER=1
      - UPLOAD_LIMIT=200M
    networks:
      jh-network:
        ipv4_address: 172.19.0.13

  # cf:
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   command: tunnel --no-autoupdate run --token eyJhIjoiNTQ0NjBhYjdkODU1NjgyZTQzZGQxZjQ2YWIxYjNlNTciLCJ0IjoiNzJmZGQ4MzktODFiNC00NTZiLWI5YzQtNjdhMzBhMWYzODU0IiwicyI6Ik1EaGpOV1EzTW1NdE1HSTNOQzAwTVRNd0xUZ3daakF0TnpReVpqRTRNV0pqWlRReiJ9
  #   volumes:
  #     - ./tunnel:/etc/cloudflared
  #   networks:
  #     jh-network:
  #       ipv4_address: 172.19.0.14

volumes:
  public-data:
networks:
  jh-network:
    driver: bridge
    name: jh-network
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1